#!/usr/bin/env bash
set -euo pipefail

# Simulates an AI agent making a code change, opening a PR, and watching it
# flow through the verification pipeline.
#
# Usage: ./scripts/simulate-agent-change.sh

BRANCH="agent/update-branding-$(date +%s)"
CHANGE_FILE="apps/web/app/(app)/environments/[environmentId]/components/EnvironmentNavbar.tsx"

echo "=== AI Agent Change Simulation ==="
echo ""

# 1. Create a feature branch
echo "1. Creating branch: ${BRANCH}"
git checkout -b "${BRANCH}"

# 2. Make a small, safe change (update a UI string)
echo "2. Making a code change..."
if [ -f "${CHANGE_FILE}" ]; then
  # Add a comment to an existing file to simulate an agent edit
  sed -i.bak '1s/^/\/\/ Agent-authored change: updated branding timestamp\n/' "${CHANGE_FILE}"
  rm -f "${CHANGE_FILE}.bak"
else
  # Fallback: create a small config change
  echo "// Agent-authored: $(date -u +%Y-%m-%dT%H:%M:%SZ)" > agent-change.ts
  CHANGE_FILE="agent-change.ts"
fi

# 3. Run CI locally via Dagger (optional, skip if Dagger not available)
if command -v dagger &>/dev/null; then
  echo "3. Running local CI via Dagger..."
  dagger call -m ci lint --src . || echo "   (lint warnings — continuing)"
else
  echo "3. Skipping local CI (Dagger not installed)"
fi

# 4. Commit and push
echo "4. Committing and pushing..."
git add -A
git commit -m "feat: update branding timestamp (agent-authored)

This change was made by an AI coding agent to demonstrate
the automated verification pipeline."

git push -u origin "${BRANCH}"

# 5. Open a PR
echo "5. Opening pull request..."
PR_URL=$(gh pr create \
  --title "feat: update branding timestamp (agent-authored)" \
  --body "$(cat <<'EOF'
## Summary

- Agent-authored change to demonstrate the CI/CD pipeline
- Updates a UI component with a branding timestamp

## Agent-Authored Change Checklist

- [x] CI passes locally (`make ci`)
- [x] No secrets or credentials in diff
- [x] No new dependencies added without justification
- [ ] cubic.dev review addressed

## What happens next

1. **CI runs** — Dagger pipeline (lint, typecheck, test, build) via GitHub Actions
2. **cubic.dev reviews** — AI code review added automatically
3. **Human approves** — Required before merge to main
4. **Deploy** — Auto-deploys to Vercel + Neon on merge

🤖 Generated by agent simulation script
EOF
)")

echo ""
echo "=== PR Created ==="
echo "${PR_URL}"
echo ""
echo "Watch the pipeline:"
echo "  - CI status checks will appear on the PR"
echo "  - cubic.dev will post an AI code review"
echo "  - A human must approve before merge to main"
echo "  - Merging triggers auto-deploy to Vercel"
